version: "3.0"
networks:
  default:
    name: dev_random_network
services:
  dev_random:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    env_file:
    - ../.env
