version: "3.0"
networks:
  default:
    name: random_hash_generator_network
services:
  random_hash_generator:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    env_file:
    - ../.env
